#!/bin/bash
set -euxo pipefail

# archive method
# commit_or_branch=${1:-origin/develop}
# _tempdir=$(mktemp -d --suffix=-git-fs)
# git archive $commit_or_branch | tar -C $_tempdir -x
# echo $_tempdir

# clone method
_tempdir=$(mktemp -d --suffix=-git-fs)
(
  commit_or_branch=${1:-zzz-origin-develop}
  remote_url=$(git remote get-url origin)
  local_url=$(pwd)
  git branch -f zzz-origin-develop origin/develop
  git clone --origin "local" --single-branch -b $commit_or_branch $local_url $_tempdir
  (
    cd $_tempdir
    git remote add upstream $remote_url
    # git remote add local $local_url
  )
) >/dev/null
echo $_tempdir
