#!/bin/bash
set -eo pipefail

repo_url="$1"
org_and_repo=$(echo $repo_url  | cut -d: -f2 | sed 's/.git$//g')

org=$(echo $org_and_repo | cut -d'/' -f1)
repo=$(echo $org_and_repo | cut -d/ -f2)

if [ -z $org ]; then
  echo -e """\033[31mCould not parse org from $repo_url
arg must be of the form git@github.com:zingales/CodeReview.git\033[m"
  exit 1
fi

if [ -z $repo ]; then
  echo -e """\033[31mCould not parse repo from $repo_url
arg must be of the form git@github.com:zingales/CodeReview.git\033[m"
  exit 1
fi

dir=~/github.com/$org/$repo

if [ ! -d $dir ]; then
  mkdir -p ~/github.com/$org/
  git clone $repo_url ~/github.com/$org/$repo
  echo $dir
  cd $dir
fi

