#!/bin/bash
SINCE_COMMIT=${1:-$(git base)}
git log $SINCE_COMMIT..HEAD --reverse --format=%h | while read -r line; do
  git log -1 $line --oneline
  git diff $line^..$line --name-only | prepend "  "
  echo
done
