#!/bin/bash

if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
  cat <<EOF
Usage: git s [<git-status-args>...]

Show current branch, last commit, and short status. All arguments are passed to git status.

Options:
  -h, --help   Show this help message
EOF
  exit 0
fi

bold=""
normal=""
if [ -t 1 ]; then
  bold=`tput bold`
  normal=`tput sgr0`
fi
echo -n "${bold}branch :: *"
git rev-parse --abbrev-ref HEAD
echo -n "${normal}"
git --no-pager log -1 --pretty=oneline --abbrev-commit
echo "--------------------- git status -------------------"
git status -s "$@"
