#!/bin/bash
bold=""
normal=""
if [ -t 1 ]; then
  bold=`tput bold`
  normal=`tput sgr0`
fi
echo -n "${bold}branch :: *"
git rev-parse --abbrev-ref HEAD
echo -n "${normal}"
git --no-pager log -1 --pretty=oneline --abbrev-commit
echo "--------------------- git status -------------------"
git status -s "$@"
