#!/bin/bash

browse=false
while getopts ":b" opt; do
  case ${opt} in
    b ) # process option a
      browse=true
      ;;
    \? ) echo "Usage: cmd [-h] [-t]"
      ;;
  esac
done

if [[ $browse = true ]];  then
  hub browse -- "pulls/ethomas-hrp"
else
 # hub issue -c ethomas-hrp --include-pulls -s all "@#"
 hub issue -c ethomas-hrp --include-pulls -f "%U %t %n"
fi
