#!/bin/bash
set -eo pipefail

CUR_BRANCH=`git rev-parse --abbrev-ref HEAD`
NEW_BRANCH="${CUR_BRANCH}_backup-$(date +%Y.%m.%d-%H.%M)"

if [ "$1" == "--create" ] || [ "$1" = "-c" ]; then
  git branch "$NEW_BRANCH"
  echo "$NEW_BRANCH"
elif [ "$1" == "--latest" ] || [ "$1" == "-l" ]; then
  echo $(git br | grep $(git tb) |  grep -v "\*" | grep "_backup-" | sort | tail -1)
else
  echo -e "\033[31mInvalid argument. Must provide --create or --latest\033[m"
  exit 1
fi
