#!/bin/bash

# Given a relative path output its absolute path. If a command line argument is given,
# it uses that, otherwise it reads from stdin.

if [ "$#" -eq 1 ]; then
    # Command line argument is provided
    echo "$(readlink -f "$1")"
else
    # No command line argument, read from stdin
    echo "$(readlink -f $(cat))"
fi
