#!/bin/bash
# Backblaze cli

# assert secret file exists
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SECRET_FILE="${SCRIPT_DIR}/.backblaze.secrets"
if [ ! -f $SECRET_FILE ]; then
  echo "secret file not found! at $SECRET_FILE"
  exit 1
fi

source $SECRET_FILE

export AWS_ACCESS_KEY_ID="$BB_KEY_ID"
export AWS_SECRET_ACCESS_KEY="$BB_APPLICATION_KEY"
export AWS_ENDPOINT_URL="$ENDPOINT_URL"

aws "$@"
