#!/usr/bin/python

import sys


def to_camel_case(s0):
    is_kebab_case = '-' in s0
    is_snake_case = '_' in s0

    if is_kebab_case:
        words = s0.split('-')
        return (
            words[0].lower() + ''.join(w.title() for w in words[1:]) if words
            else ''
        )
    elif is_snake_case:
        words = s0.split('_')
        return (
            words[0].lower() + ''.join(w.title() for w in words[1:]) if words
            else ''
        )
    else:
        return s0


for line in sys.stdin.readlines():
    print(to_camel_case(line.strip()))
