#!/bin/bash
bold=[ -t 1 ] && `tput bold`
normal=[ -t 1 ] && `tput sgr0`
echo -n "${bold}branch :: *"
git rev-parse --abbrev-ref HEAD
echo -n "${normal}"
git --no-pager log -1 --pretty=oneline --abbrev-commit
echo "--------------------- git status -------------------"
git status -s "$@"
