#!/usr/bin/python

import sys
import re

# not using string.uppercase to be python2/python3 compatible
uppercase = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
lowercase = 'abcdefghijklmnopqrstuvwxyz'


def to_kebab_case(s0):
    is_snake_case = '_' in s0
    is_camel_case = (
        any(x in s0 for x in uppercase) and
        any(x in s0 for x in lowercase)
    )

    if is_snake_case:
        return re.sub('_', r'-', s0)
    elif is_camel_case:
        # modified from
        # https://www.geeksforgeeks.org/python-program-to-convert-camel-case-string-to-snake-case/
        s1 = re.sub('(.)([A-Z][a-z]+)', r'\1-\2', s0)
        return re.sub('([a-z0-9])([A-Z])', r'\1-\2', s1).lower()
    else:
        return s0


for line in sys.stdin.readlines():
    print(to_kebab_case(line.strip()))
