#!/bin/bash

# generic
export http_proxy=http://localhost:8080/
export HTTP_PROXY=http://localhost:8080/
export https_proxy=http://localhost:8080/
export HTTPS_PROXY=http://localhost:8080/

# curl I think???
export CURL_CA_BUNDLE=~/.mitmproxy/mitmproxy-ca-cert.cer
export SSL_CERT_FILE=~/.mitmproxy/mitmproxy-ca-cert.cer

# node
export NODE_USE_ENV_PROXY=1
export NODE_EXTRA_CA_CERTS=~/.mitmproxy/mitmproxy-ca-cert.cer

exec "$@"
