#!/bin/bash

docker network create mitmweb

docker run --rm -it \
  --name mitmproxy \
  -v ~/.mitmproxy:/home/mitmproxy/.mitmproxy   \
  -p 8080:8080   \
  -p 8081:8081   \
  --network=mitmweb \
  mitmproxy/mitmproxy   \
  mitmweb  \
  --web-host 0.0.0.0
