#!/usr/bin/python

import re
import sys

# not using string.uppercase to be python2/python3 compatible
uppercase = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
lowercase = 'abcdefghijklmnopqrstuvwxyz'


def to_snake_case(s0):
    is_kebab_case = '-' in s0
    is_camel_case = (
        any(x in s0 for x in uppercase) and
        any(x in s0 for x in lowercase)
    )
    if is_kebab_case:
        return re.sub('-', r'_', s0)
    elif is_camel_case:
        # https://www.geeksforgeeks.org/python-program-to-convert-camel-case-string-to-snake-case/
        s1 = re.sub('(.)([A-Z][a-z]+)', r'\1_\2', s0)
        return re.sub('([a-z0-9])([A-Z])', r'\1_\2', s1).lower()
    else:
        return s0


for line in sys.stdin.readlines():
    print(to_snake_case(line.strip()))
