#!/usr/bin/env python

import yaml
import json
import sys
import contextlib

if len(sys.argv) >= 2:
    with open(sys.argv[1]) as f:
        d = yaml.load(f)
else:
    d = yaml.safe_load(sys.stdin.read())
print(json.dumps(d))
